### ISSUE TITLE
Glia fails to insert point processes on v3.0.0b0 

### ISSUE THREAD

**Issue by Helveg** [Helveg/patch#42]
Could be Glia, could be us:

```
>>> import glia
>>> import patch
numprocs=1
>>> glia.insert(patch.p.Section(), "AMPA")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/robin/glia/glia/__init__.py", line 34, in insert
    section, asset, attributes=attributes, pkg=pkg, variant=variant, x=x
  File "/home/robin/glia/glia/_glia.py", line 30, in wrapper
    return func(self, *args, **kwargs)
  File "/home/robin/glia/glia/_glia.py", line 263, in insert
    ) from None
glia.exceptions.LibraryError: 'glia__dbbs_mod_collection__AMPA__0' point process not found 
>>> patch.__version__
'3.0.0b0'
```

**Comment by Helveg** [comment]
Seems fixed:

```
>>> import glia
>>> import patch
numprocs=1
>>> glia.insert(patch.p.Section(), "AMPA")
<patch.objects.PointProcess object pointing to 'glia__dbbs_mod_collection__AMPA__0[0]'>
```
